import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./types"; // generated by openapi-typescript

const API_BASE_URL = import.meta.env.VITE_API_URL as string | undefined;

if (!API_BASE_URL) {
  throw new Error("VITE_API_URL environment variable is not defined");
}

export const fetchClient = createFetchClient<paths>({
  baseUrl: API_BASE_URL,
});

export const $api = createClient(fetchClient);