/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/routes/{route_short_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Route */
        get: operations["get_route_routes__route_short_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{route_short_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Vehicle Positions */
        get: operations["get_vehicle_positions_vehicles__route_short_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LatLon */
        LatLon: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
        };
        /** Route */
        Route: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Stops */
            stops: components["schemas"]["Stop"][];
        };
        /** Stop */
        Stop: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            position: components["schemas"]["LatLon"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vehicle */
        Vehicle: {
            /** Id */
            id: string;
            position: components["schemas"]["VehiclePosition"];
            /** Trip Id */
            trip_id: string;
            /** Next Stop Id */
            next_stop_id: string;
            /** Next Stop Scheduled Arrival Time */
            next_stop_scheduled_arrival_time: number;
            /** Next Stop Estimated Arrival Time */
            next_stop_estimated_arrival_time: number;
        };
        /** VehiclePosition */
        VehiclePosition: {
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Bearing */
            bearing: number;
            /** Speed */
            speed: number;
            /** Odometer */
            odometer: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_route_routes__route_short_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_short_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Route"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_vehicle_positions_vehicles__route_short_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_short_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicle"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
