import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api/types"; // generated by openapi-typescript
import {Map, Layer, Source, type MapRef, Marker, Popup} from '@vis.gl/react-maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import type {Feature, LineString, Point} from "geojson";
import { useCallback, useMemo, useRef } from "react";
import React from "react";
import { $api } from "./api";

const ICON = `M20.2,15.7L20.2,15.7c1.1-1.6,1.8-3.6,1.8-5.7c0-5.6-4.5-10-10-10S2,4.5,2,10c0,2,0.6,3.9,1.6,5.4c0,0.1,0.1,0.2,0.2,0.3
  c0,0,0.1,0.1,0.1,0.2c0.2,0.3,0.4,0.6,0.7,0.9c2.6,3.1,7.4,7.6,7.4,7.6s4.8-4.5,7.4-7.5c0.2-0.3,0.5-0.6,0.7-0.9
  C20.1,15.8,20.2,15.8,20.2,15.7z`;

interface PinProps {
  size?: number;
  fillColor: string;
  strokeColor: string;
}

function Pin({size = 20, fillColor, strokeColor}: PinProps) {
  return (
    <svg height={size} viewBox="0 0 24 24" style={{
      fill: fillColor,
      stroke: strokeColor,
    }}>
      <path d={ICON} />
    </svg>
  );
}

export default React.memo(Pin);

const stockholmCenter = { lng: 18.063, lat: 59.334 };

interface StopHoverInfo {
  id: string;
  name: string;
  longitude: number;
  latitude: number;
}

export interface RouteLayerProps {
  routeName: string;
  lineColor: string;
  stopColor: string;
  setSelectedStop?: (stopInfo: StopHoverInfo | null) => void;
}

export const RouteComponent = ({routeName, lineColor, stopColor,
  setSelectedStop
}: RouteLayerProps) => {
  const { data, error, isLoading } = $api.useQuery(
    "get",
    "/routes/{route_short_name}",
    {
      params: {
        path: { route_short_name: routeName },
      },
    },
  );

  const geoJson = useMemo<GeoJSON.FeatureCollection<LineString | Point> | undefined>(() => data ? ({
    'type': 'FeatureCollection',
    'features': [
      {
        'type': 'Feature',
        'properties': {},
        'geometry': {
          'type': 'LineString',
          'coordinates': data.stops.map(stop => [stop.position.longitude, stop.position.latitude])
        }
      },
      ...data.stops.map(stop => ({
        'type': 'Feature',
        'properties': { id: stop.id, name: stop.name },
        'geometry': {
          'type': 'Point',
          'coordinates': [stop.position.longitude, stop.position.latitude]
        }
      } as Feature<Point>))
    ]
  }): undefined, [data]);

  if (isLoading || !data) return undefined;

  if (error) return `An error occured: ${error.detail}`;

  return (<>
    {geoJson && <>
      <Source type="geojson" data={geoJson}>
        <Layer
          type="line"
          filter={['==', '$type', 'LineString']}
          layout={{
              'line-join': 'round',
              'line-cap': 'round'
          }}
          paint={{
            'line-color': lineColor,
            "line-width": 2,
          }}
        />
        <Layer
          type="circle"
          filter={['==', '$type', 'Point']}
          paint={{
            'circle-radius': 5,
            'circle-color': stopColor,
            'circle-stroke-width': 1,
            'circle-stroke-color': "#FFFFFF"
          }}
        />
      </Source>
    </>}
  </>);
};

export interface RouteVehiclePositionsProps {
  routeName: string;
  vehicleColor: string;
  vehicleStrokeColor: string;
  onHover?: (hoverInfo: HoverInfo | null) => void;
}

export const RouteVehiclePositions = ({routeName, vehicleColor, vehicleStrokeColor, onHover}: RouteVehiclePositionsProps) => {
  const { data, error, isLoading } = $api.useQuery(
    "get",
    "/vehicles/{route_short_name}",
    {
      params: {
        path: { route_short_name: routeName },
      },
    },
    {
      refetchInterval: 15_000,
    }
  );

  if (isLoading || !data) return undefined;

  if (error) return `An error occured: ${error.detail}`;

  return (<>
    {data && <>
      {data.map((vehicle) => (

        <Marker
          key={vehicle.id}
          longitude={vehicle.position.longitude}
          latitude={vehicle.position.latitude}
          anchor="bottom"
          rotation={vehicle.position.bearing}
          rotationAlignment="map"
          onClick={(e) => {
            e.originalEvent.stopPropagation();
            console.log("Clicked vehicle", vehicle.id);
            onHover?.({
              longitude: vehicle.position.longitude,
              latitude: vehicle.position.latitude,
              vehicleId: vehicle.id,
              tripId: vehicle.trip_id,
              nextStopId: vehicle.next_stop_id,
              scheduledArrivalTime: vehicle.next_stop_scheduled_arrival_time,
              estimatedArrivalTime: vehicle.next_stop_estimated_arrival_time ?? undefined,
            })
          }}
        >
          <Pin size={15} fillColor={vehicleColor} strokeColor={vehicleStrokeColor} />
        </Marker>
        
      ))}
    </>}
  </>);
}

interface HoverInfo {
  longitude: number;
  latitude: number;
  vehicleId: string;
  tripId: string;
  nextStopId: string;
  scheduledArrivalTime?: number;
  estimatedArrivalTime?: number;
}

export interface MapComponentProps {
}

const HOUR_MS = 3600 * 1000;

export const MapComponent = ({}: MapComponentProps) => {
  const RED_LINE = ["#FF0000", "#DF0000"];
  const RED_LINE_BUSES = ["#CC0000", "#AA0000"];
  const GREEN_LINE = ["#00FF00", "#00DF00"];
  const GREEN_LINE_BUSES = ["#00CC00", "#00AA00"];
  const YELLOW_LINE = ["#FFFF00", "#DFDF00"];
  const YELLOW_LINE_BUSES = ["#CCCC00", "#AAAA00"];
  const BLUE_LINE = ["#0000FF", "#0000DF"];
  const BLUE_LINE_BUSES = ["#0000CC", "#0000AA"];

  const map = useRef<MapRef>(null);

  const [hoverInfo, setHoverInfo] = React.useState<HoverInfo | null>(null);

  console.log({hoverInfo});

  return (<>
    <Map
      ref={map}
      initialViewState={{
        longitude: stockholmCenter.lng,
        latitude: stockholmCenter.lat,
        zoom: 11
      }}
      style={{width: "100%", height: "100%"}}
      mapStyle="https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json"
      onClick={() => setHoverInfo(null)}
    >
      <RouteComponent routeName="1" lineColor={GREEN_LINE[0]} stopColor={GREEN_LINE[1]} />
      <RouteVehiclePositions routeName="1" vehicleColor={GREEN_LINE_BUSES[0]} vehicleStrokeColor={GREEN_LINE_BUSES[1]} onHover={setHoverInfo} />
      <RouteComponent routeName="2" lineColor={YELLOW_LINE[0]} stopColor={YELLOW_LINE[1]} />
      <RouteVehiclePositions routeName="2" vehicleColor={YELLOW_LINE_BUSES[0]} vehicleStrokeColor={YELLOW_LINE_BUSES[1]} onHover={setHoverInfo} />
      <RouteComponent routeName="3" lineColor={RED_LINE[0]} stopColor={RED_LINE[1]} />
      <RouteVehiclePositions routeName="3" vehicleColor={RED_LINE_BUSES[0]} vehicleStrokeColor={RED_LINE_BUSES[1]} onHover={setHoverInfo} />
      <RouteComponent routeName="4" lineColor={BLUE_LINE[0]} stopColor={BLUE_LINE[1]} />
      <RouteVehiclePositions routeName="4" vehicleColor={BLUE_LINE_BUSES[0]} vehicleStrokeColor={BLUE_LINE_BUSES[1]} onHover={setHoverInfo} />

      {hoverInfo && (
        <Popup
          longitude={hoverInfo.longitude}
          latitude={hoverInfo.latitude}
          closeButton={true}
          className="text-black"
          onClose={() => setHoverInfo(null)}
        >
          <div className="p-2">
            <p>Vehicle ID: {hoverInfo.vehicleId}</p>
            <p>Trip ID: {hoverInfo.tripId}</p>
            <p>Next Stop ID: {hoverInfo.nextStopId}</p>
            <p>Scheduled Arrival Time: {hoverInfo.scheduledArrivalTime ? new Date(hoverInfo.scheduledArrivalTime * 1000 - HOUR_MS).toLocaleTimeString("sv-SE") : "N/A"}</p>
            <p>Estimated Arrival Time: {hoverInfo.estimatedArrivalTime ? new Date(hoverInfo.estimatedArrivalTime * 1000 - HOUR_MS).toLocaleTimeString("sv-SE") : "N/A"}</p>

          </div>
        </Popup>
      )}
    </Map>
  </>);
};