import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api/types"; // generated by openapi-typescript
import {Map, Layer, Source, type MapRef, Marker} from '@vis.gl/react-maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import type {Feature, LineString, Point} from "geojson";
import { useMemo, useRef } from "react";
import React from "react";

const ICON = `M20.2,15.7L20.2,15.7c1.1-1.6,1.8-3.6,1.8-5.7c0-5.6-4.5-10-10-10S2,4.5,2,10c0,2,0.6,3.9,1.6,5.4c0,0.1,0.1,0.2,0.2,0.3
  c0,0,0.1,0.1,0.1,0.2c0.2,0.3,0.4,0.6,0.7,0.9c2.6,3.1,7.4,7.6,7.4,7.6s4.8-4.5,7.4-7.5c0.2-0.3,0.5-0.6,0.7-0.9
  C20.1,15.8,20.2,15.8,20.2,15.7z`;

interface PinProps {
  size?: number;
  fillColor: string;
  strokeColor: string;
}

function Pin({size = 20, fillColor, strokeColor}: PinProps) {
  return (
    <svg height={size} viewBox="0 0 24 24" style={{
      fill: fillColor,
      stroke: strokeColor,
    }}>
      <path d={ICON} />
    </svg>
  );
}

export default React.memo(Pin);

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:8000",
});
const $api = createClient(fetchClient);

const stockholmCenter = { lng: 18.063, lat: 59.334 };

export interface RouteLayerProps {
  routeName: string;
  lineColor: string;
  stopColor: string;
}

export const RouteComponent = ({routeName, lineColor, stopColor}: RouteLayerProps) => {
  const { data, error, isLoading } = $api.useQuery(
    "get",
    "/routes/{route_short_name}",
    {
      params: {
        path: { route_short_name: routeName },
      },
    },
  );

  const geoJson = useMemo<GeoJSON.FeatureCollection<LineString | Point> | undefined>(() => data ? ({
    'type': 'FeatureCollection',
    'features': [
      {
        'type': 'Feature',
        'properties': {},
        'geometry': {
          'type': 'LineString',
          'coordinates': data.stops.map(stop => [stop.position.longitude, stop.position.latitude])
        }
      },
      ...data.stops.map(stop => ({
        'type': 'Feature',
        'properties': { name: stop.name },
        'geometry': {
          'type': 'Point',
          'coordinates': [stop.position.longitude, stop.position.latitude]
        }
      } as Feature<Point>))
    ]
  }): undefined, [data]);

  console.log({geoJson});

  if (isLoading || !data) return undefined;

  if (error) return `An error occured: ${error.detail}`;

  return (<>
    {geoJson && <>
      <Source type="geojson" data={geoJson}>
        <Layer
          type="line"
          filter={['==', '$type', 'LineString']}
          layout={{
              'line-join': 'round',
              'line-cap': 'round'
          }}
          paint={{
            'line-color': lineColor,
            "line-width": 2,
          }}
        />
        <Layer
          type="circle"
          filter={['==', '$type', 'Point']}
          paint={{
            'circle-radius': 5,
            'circle-color': stopColor,
            'circle-stroke-width': 1,
            'circle-stroke-color': "#FFFFFF"
          }}
        />
      </Source>
    </>}
  </>);
};

export interface RouteVehiclePositionsProps {
  routeName: string;
  vehicleColor: string;
  vehicleStrokeColor: string;
}

export const RouteVehiclePositions = ({routeName, vehicleColor, vehicleStrokeColor}: RouteVehiclePositionsProps) => {
  const { data, error, isLoading } = $api.useQuery(
    "get",
    "/vehicles/{route_short_name}",
    {
      params: {
        path: { route_short_name: routeName },
      },
    },
    {
      refetchInterval: 15_000,
    }
  );

  if (isLoading || !data) return undefined;

  if (error) return `An error occured: ${error.detail}`;

  return (<>
    {data && <>
      {data.map((vehicle) => (

        <Marker
          longitude={vehicle.position.longitude}
          latitude={vehicle.position.latitude}
          anchor="bottom"
          draggable
          rotation={vehicle.position.bearing}
          rotationAlignment="map"
        >
          <Pin size={15} fillColor={vehicleColor} strokeColor={vehicleStrokeColor} />
        </Marker>
        
      ))}
    </>}
  </>);
}

export interface MapComponentProps {
}

export const MapComponent = ({}: MapComponentProps) => {
  const RED_LINE = ["#FF0000", "#DF0000"];
  const RED_LINE_BUSES = ["#CC0000", "#AA0000"];
  const GREEN_LINE = ["#00FF00", "#00DF00"];
  const GREEN_LINE_BUSES = ["#00CC00", "#00AA00"];
  const YELLOW_LINE = ["#FFFF00", "#DFDF00"];
  const YELLOW_LINE_BUSES = ["#CCCC00", "#AAAA00"];
  const BLUE_LINE = ["#0000FF", "#0000DF"];
  const BLUE_LINE_BUSES = ["#0000CC", "#0000AA"];

  const map = useRef<MapRef>(null);

  return (<>
    <Map
      ref={map}
      initialViewState={{
        longitude: stockholmCenter.lng,
        latitude: stockholmCenter.lat,
        zoom: 11
      }}
    style={{width: "100%", height: "100%"}}
      mapStyle="https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json"
    >
      <RouteComponent routeName="1" lineColor={GREEN_LINE[0]} stopColor={GREEN_LINE[1]} />
      <RouteVehiclePositions routeName="1" vehicleColor={GREEN_LINE_BUSES[0]} vehicleStrokeColor={GREEN_LINE_BUSES[1]} />
      <RouteComponent routeName="2" lineColor={YELLOW_LINE[0]} stopColor={YELLOW_LINE[1]} />
      <RouteVehiclePositions routeName="2" vehicleColor={YELLOW_LINE_BUSES[0]} vehicleStrokeColor={YELLOW_LINE_BUSES[1]} />
      <RouteComponent routeName="3" lineColor={RED_LINE[0]} stopColor={RED_LINE[1]} />
      <RouteVehiclePositions routeName="3" vehicleColor={RED_LINE_BUSES[0]} vehicleStrokeColor={RED_LINE_BUSES[1]} />
      <RouteComponent routeName="4" lineColor={BLUE_LINE[0]} stopColor={BLUE_LINE[1]} />
      <RouteVehiclePositions routeName="4" vehicleColor={BLUE_LINE_BUSES[0]} vehicleStrokeColor={BLUE_LINE_BUSES[1]} />
    </Map>
  </>);
};