import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./api/types"; // generated by openapi-typescript
import {Map, Layer, Source} from '@vis.gl/react-maplibre';
import 'maplibre-gl/dist/maplibre-gl.css';
import type {Feature, LineString, Point} from "geojson";
import { useMemo } from "react";

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:8000",
});
const $api = createClient(fetchClient);

const stockholmCenter = { lng: 18.063, lat: 59.334 };

export interface RouteLayerProps {
  routeName: string;
  lineColor: string;
  stopColor: string;
}

export const RouteComponent = ({routeName, lineColor, stopColor}: RouteLayerProps) => {
  const { data, error, isLoading } = $api.useQuery(
    "get",
    "/routes/{route_short_name}",
    {
      params: {
        path: { route_short_name: routeName },
      },
    },
  );

  const geoJson = useMemo<GeoJSON.FeatureCollection<LineString | Point> | undefined>(() => data ? ({
    'type': 'FeatureCollection',
    'features': [
      {
        'type': 'Feature',
        'properties': {},
        'geometry': {
          'type': 'LineString',
          'coordinates': data.stops.map(stop => [stop.position.longitude, stop.position.latitude])
        }
      },
      ...data.stops.map(stop => ({
        'type': 'Feature',
        'properties': { name: stop.name },
        'geometry': {
          'type': 'Point',
          'coordinates': [stop.position.longitude, stop.position.latitude]
        }
      } as Feature<Point>))
    ]
  }): undefined, [data]);

  console.log({geoJson});

  if (isLoading || !data) return undefined;

  if (error) return `An error occured: ${error.detail}`;

  return (<>
    {geoJson && <>
      <Source type="geojson" data={geoJson}>
        <Layer
          type="line"
          filter={['==', '$type', 'LineString']}
          layout={{
              'line-join': 'round',
              'line-cap': 'round'
          }}
          paint={{
            'line-color': lineColor,
            "line-width": 2,
          }}
        />
        <Layer
          type="circle"
          filter={['==', '$type', 'Point']}
          paint={{
            'circle-radius': 5,
            'circle-color': stopColor,
            'circle-stroke-width': 1,
            'circle-stroke-color': "#FFFFFF"
          }}
        />
      </Source>
    </>}
  </>);
};

export interface MapComponentProps {
}

export const MapComponent = ({}: MapComponentProps) => {
  const RED_LINE = ["#FF0000", "#DF0000"];
  const GREEN_LINE = ["#00FF00", "#00DF00"];
  const YELLOW_LINE = ["#FFFF00", "#DFDF00"];
  const BLUE_LINE = ["#0000FF", "#0000DF"];

  return (<>
    <Map
      initialViewState={{
        longitude: stockholmCenter.lng,
        latitude: stockholmCenter.lat,
        zoom: 11
      }}
    style={{width: 800, height: 800}}
      mapStyle="https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json"
    >
      <RouteComponent routeName="1" lineColor={GREEN_LINE[0]} stopColor={GREEN_LINE[1]} />
      <RouteComponent routeName="2" lineColor={YELLOW_LINE[0]} stopColor={YELLOW_LINE[1]} />
      <RouteComponent routeName="3" lineColor={RED_LINE[0]} stopColor={RED_LINE[1]} />
      <RouteComponent routeName="4" lineColor={BLUE_LINE[0]} stopColor={BLUE_LINE[1]} />
    </Map>
  </>);
};